package output

import (
    "fmt"
    "hasseg.org/sanat/model"
)

func AppleStringFromSegments(segments []model.TranslationValueSegment) string {
    // TODO
    ret := ""
    for _,segment := range segments {
        ret += segment.Text
    }
    return ret
}

func WriteAppleStringsFile(set model.TranslationSet, language string) {
    fmt.Println("/**\n" +
                " * Apple Strings File\n" +
                " * Generated by TODO\n" +
                " * Language: " + language + "\n" +
                " */")
    for _,section := range set.Sections {
        fmt.Println("\n/********** " + section.Name + " **********/\n")
        for _,translation := range section.Translations {
            for _,value := range translation.Values {
                if value.Language == language {
                    fmt.Printf("\"%s\" = \"%s\";\n",
                               translation.Key,
                               AppleStringFromSegments(value.Segments))
                }
            }
        }
    }
}
